// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package di

import (
	"movie_service/internal/app/interface/read/in_memory"
	"movie_service/internal/app/interface/read/redis"
	"movie_service/internal/app/interface/read/tmdb"
	"movie_service/internal/app/interface/rpc/v1"
	"movie_service/internal/app/use_case"
)

// Injectors from wire.go:

func InitializeMovieService() v1.MovieService {
	cache := redis.NewRedisCache()
	movieQuery := tmdb.NewQuery(cache)
	useCase := use_case.NewInterActor(movieQuery)
	movieService := v1.NewMovieService(useCase)
	return movieService
}

func InitializeTestMovieService() v1.MovieService {
	movieQuery := in_memory.NewQuery()
	useCase := use_case.NewInterActor(movieQuery)
	movieService := v1.NewMovieService(useCase)
	return movieService
}
